//
//  GalleryWorker.swift
//  SwiftBoilerplate
//
//  Created by Fachri Work on 1/9/18.
//  Copyright (c) 2018 Fachri Febrian. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GalleryWorker {

  func doSomeWork() {
  
  }
}
