//
//  GalleryInteractor.swift
//  SwiftBoilerplate
//
//  Created by Fachri Work on 1/9/18.
//  Copyright (c) 2018 Fachri Febrian. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GalleryBusinessLogic {
  func doSomething(request: Gallery.Something.Request)
}

protocol GalleryDataStore {
  //var name: String { get set }
}

class GalleryInteractor: GalleryBusinessLogic, GalleryDataStore {
  var presenter: GalleryPresentationLogic?
  var worker: GalleryWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Gallery.Something.Request) {
    worker = GalleryWorker()
    worker?.doSomeWork()
    
    let response = Gallery.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
